[package]
name = "diode"
version = "2.0.0"
edition = "2024"
license = "GPL-3.0"

[workspace]
members = [".", "diode-file-bindings"]

[dependencies]
clap = { version = "4", features = ["color", "derive", "error-context", "help", "std", "suggestions", "usage"] }
core_affinity = "0"
crossbeam-channel = "0"
crossbeam-utils = "0"
fasthash = "0"
libc = "0"
log = "0"
rand = "0"
raptorq = "2"
semka = "2"
simplelog = "0"

[profile.release]
opt-level = 3
lto = true
debug = false
strip = true
panic = "abort"
codegen-units = 1

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
must_use_candidate = "allow"
enum-glob-use = "allow"
missing-errors-doc = "allow"
